# .readthedocs.yaml

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    post:
      - mkdir -p /home/docs/checkouts/readthedocs.org/user_builds/{project-name}/envs/latest/src
      - cp -r docs /home/docs/checkouts/readthedocs.org/user_builds/{project-name}/envs/latest/src

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .

  extra_requirements:
    - docs

# Optionally, add these if you have extra requirements
# requirements_file: docs/requirements.txt

conda:
  environment: docs/environment.yml
